// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PI.Core.DataContext;

#nullable disable

namespace PI.Core.Migrations
{
    [DbContext(typeof(AutoCompManagerContext))]
    [Migration("20240606212819_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PI.Domain.Models.Ramp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("IdSquad")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdSquad");

                    b.ToTable("Ramp", "dbo");
                });

            modelBuilder.Entity("PI.Domain.Models.Speed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("BurnedStart")
                        .HasColumnType("bit");

                    b.Property<int>("CutWay")
                        .HasColumnType("int");

                    b.Property<int>("IdSquad")
                        .HasColumnType("int");

                    b.Property<int>("OutsideLine")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.Property<double>("TimeWithoutPenalties")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdSquad");

                    b.ToTable("Speed", "dbo");
                });

            modelBuilder.Entity("PI.Domain.Models.Squad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Squad", "dbo");
                });

            modelBuilder.Entity("PI.Domain.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("IdSquad")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdSquad");

                    b.ToTable("Student", "dbo");
                });

            modelBuilder.Entity("PI.Domain.Models.Traction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdSquad")
                        .HasColumnType("int");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdSquad");

                    b.ToTable("Traction", "dbo");
                });

            modelBuilder.Entity("PI.Domain.Models.Ramp", b =>
                {
                    b.HasOne("PI.Domain.Models.Squad", "Squad")
                        .WithMany("Ramp")
                        .HasForeignKey("IdSquad");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("PI.Domain.Models.Speed", b =>
                {
                    b.HasOne("PI.Domain.Models.Squad", "Squad")
                        .WithMany("Speed")
                        .HasForeignKey("IdSquad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("PI.Domain.Models.Student", b =>
                {
                    b.HasOne("PI.Domain.Models.Squad", "Squad")
                        .WithMany("Student")
                        .HasForeignKey("IdSquad");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("PI.Domain.Models.Traction", b =>
                {
                    b.HasOne("PI.Domain.Models.Squad", "Squad")
                        .WithMany("Traction")
                        .HasForeignKey("IdSquad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("PI.Domain.Models.Squad", b =>
                {
                    b.Navigation("Ramp");

                    b.Navigation("Speed");

                    b.Navigation("Student");

                    b.Navigation("Traction");
                });
#pragma warning restore 612, 618
        }
    }
}
